### ISSUE TITLE
GIDSignIn.signIn getting "keychain error" for some users

### ISSUE THREAD

**Issue by alperkayabasi** [google/GoogleSignIn-iOS#165]
Hello, 

We are using Google Sign In for a few years. Suddenly, some users start to get "com.google.GIDSignIn keychain error" and we can't sign them in to our application.

To fix this, I have to enable "keychain access" on my project settings (we have never enabled this and it was working as expected for a long time) and add "com.google.GIDSignIn" as keychain group.
Here is the screenshot;
![Screen Shot 2022-05-30 at 14 04 57](https://user-images.githubusercontent.com/2501751/170979943-314b4fbe-3ec2-443b-86e1-c33bc781b726.png)
If I use my own bundle id here I still get the same error, I have to add com.google.GIDSignIn specifically.

This is not one of the steps to integrate the SDK and I don't think why it is neccessary to add "com.google.GIDSignIn" keychain access in my project.

Can you help with the issue?
Thank you.

**Comment by petea** [comment]
Can you tell me what version of Google Sign-In you're using when you see this behavior?  The version of GTMAppAuth you're building with would also be relevant, as well as the version(s) of iOS you're seeing this on.

**Comment by tuando3i** [comment]
We are having the same problem here.
- GMTAppAuth: 1.2.3
- iOS version 15.5 (notice that it happens to some phones not happen with some other phones)

**Comment by AndyActionItem** [comment]
Also seeing this with iOS 15.5, GTMAppAuth 1.2.3. It was reported today. Still looking to see if the version of iOS is a determining factor. This is an app that is in the store.

**Comment by alperkayabasi** [comment]
- GoogleSignIn (6.1.0)
- GTMAppAuth (1.2.2)

The device I debugged was iOS 15.5 but there are many users who reported the issue, I don't know the OS versions of all.

**Comment by sopherwang** [comment]
I'm also having the same issue. Any suggestions would be great.

**Comment by petea** [comment]
If you can reproduce this in a debug build, try setting a breakpoint in GTMAppAuth's `GTMKeychain` implementation in the -setPasswordData:forService:accessibility:account:error: method and check the return value of the `SecItemAdd` call.  A non-zero value of `status` could provide some insight into what type of a Keychain error we're dealing with.

**Comment by zaidhafeez** [comment]
The "keyChain Error" is not shown in an updated version of GTMAppAuth (1.3.0).
Just updated to the newest version to resolve the error.

**Comment by zaidhafeez** [comment]
> If you can reproduce this in a debug build, try setting a breakpoint in GTMAppAuth's `GTMKeychain` implementation in the -setPasswordData:forService:accessibility:account:error: method and check the return value of the `SecItemAdd` call. A non-zero value of `status` could provide some insight into what type of a Keychain error we're dealing with.

The status returned in GTMAppAuth (1.2.2). is `errSecDuplicateItem`.

**Comment by petea** [comment]
@zaidhafeez thanks for the feedback.

For anyone who is (or was) experiencing this behavior, could you tell me all the third-party libraries you're using and how they're being built / linked (SPM, CocoaPods, XCFrameworks, etc).  I'm looking for a potential source of conflicting Keychain operations.

**Comment by iyouqiang** [comment]
GoogleSignIn(5.0.2)   iOS 15.4.1

**Comment by alperkayabasi** [comment]
I can verify that "keychain error" doesn't occur on GTMAppAuth version (1.3.0).
It still persists on 1.2.2 though.

**Comment by petea** [comment]
@alperkayabasi could you let me know which (if any) third-party libraries you're using in addition to Google Sign-In?  Please see my [previous comment](https://github.com/google/GoogleSignIn-iOS/issues/165#issuecomment-1145137355).

**Comment by alperkayabasi** [comment]
@petea We're using a lot of 3rd party frameworks but I'll try to list major ones.

```
pod 'Alamofire'

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Performance'
pod 'Firebase/Crashlytics'
pod 'GoogleAppMeasurement'

pod 'Google-Mobile-Ads-SDK'
pod 'GoogleSignIn'

pod 'FBSDKCoreKit'
pod 'FBAudienceNetwork'
pod 'FBSDKLoginKit'

pod 'Adjust'
pod 'AppsFlyerFramework'

pod 'CryptoSwift'
pod 'KeychainSwift'
pod 'TikTokOpenSDK'
pod 'SwiftyVK'
```

**Comment by longvudai** [comment]
Upgrade to 6.2.2 solve my keychain error problem.

**Comment by sugitatestblue** [comment]
@iyouqiang
I use same version.


I resolved by upgrading 6.0.0 version. but I don't wanna upgrade.

I deleted the app once, but I can't login.
Although I logged in with 6.0.0 version and logout, I can't login with 5.0.2.

Anyone can resolved?

**Comment by SimmaAulakh** [comment]
I am also getting the same error for my application. It was working well before.

**Comment by kvacquier** [comment]
Same here, got the issue on my phone with multiple accounts

**Comment by gy6177** [comment]
I have the same problem
  - GoogleSignIn (6.1.0):
    - AppAuth (~> 1.4)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)

**Comment by petea** [comment]
For those who are still seeing this issue, please let me know which versions of GoogleSignIn and GTMAppAuth you're building with.

**Comment by gy6177** [comment]
GoogleSignIn  -> 6.1.0
GTMAppAuth  -> 1.0
在 iOS 15.4 和 iOS 15.0 都遇到了

**Comment by gy6177** [comment]
Upgrade to Google signin 6.2.2 without this problem. The following is the corresponding version
  - GoogleSignIn (6.2.2):
    - AppAuth (~> 1.5)
    - GTMAppAuth (~> 1.3)

**Comment by tylerexmg** [comment]
Also seeing this issue on iOS 16 beta:

GoogleSignIn (6.1.0):
    - AppAuth (~> 1.4)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)

**Comment by CharlyDev75** [comment]
We're running version 6.1.0 and some of our users are experiencing this issue in too.
Is there a version that you recommend to upgrade to solve this?
Thanks

**Comment by Simon-Zeng** [comment]
> 

Update to latest version which has GTMAppAuth  ~> 1.3 will fix the issue

**Comment by CharlyDev75** [comment]
> > 
> 
> Update to latest version which has GTMAppAuth ~> 1.3 will fix the issue

Thanks a lot Simon!

**Comment by sgiraldog** [comment]
Updating to latest version solved the issue!

**Comment by iprabhakarpatil** [comment]
> After updating my pods to `Installing AppAuth 1.6.0 (was 1.5.0) Installing GTMAppAuth 1.3.1 (was 1.3.0) Installing GoogleSignIn 6.2.4 (was 6.2.2)`
> 
> I reproduced the issue on a Mac Silicon with Mac OS Ventura (13.0 (22A380)). But It works on iPad OS 16.1.

Same here.
Facing the issue in MacOS testflight builds, but works fine in iOS devices.

**Comment by flipflopworld** [comment]
What I am seeing is here...

**TestFlight Build (with latest SignIn SDK)**

iPhone 13 / iOS 16.1 - working fine
iPhone XR / iOS 15.6 - working fine
iPhone 6S / iOS 15.6.1  - working fine

**AppStore Build (with old SignIn SDK)**

iPhone 13 / iOS 16.1 - Keychain error
iPhone XR / iOS 15.6 - working fine
iPhone 6S / iOS 15.6.1  - working fine

**Comment by jonsutherland** [comment]
> > After updating my pods to `Installing AppAuth 1.6.0 (was 1.5.0) Installing GTMAppAuth 1.3.1 (was 1.3.0) Installing GoogleSignIn 6.2.4 (was 6.2.2)`
> > I reproduced the issue on a Mac Silicon with Mac OS Ventura (13.0 (22A380)). But It works on iPad OS 16.1.
> 
> Same here. Facing the issue in MacOS testflight builds, but works fine in iOS devices.

Same issue with MacOS testflight build on Apple Silicon, but works fine on any iOS device I've tried

**Comment by binnilalnamshi** [comment]
I am facing the same issue even upgraded to GoogleSignIn version 7.0.0 and GTMAppAuth version 2.0.0. But it happening in TestFlight builds and not reproduced in App Store builds yet.

**Comment by binnilalnamshi** [comment]
> For those who are still seeing this issue, please let me know which versions of GoogleSignIn and GTMAppAuth you're building with.

Still I am facing this issue in some devices. Here are the versions of GooglrSignIn

- GoogleSignIn (7.0.0):
    - AppAuth (~> 1.5)
    - GTMAppAuth (< 3.0, >= 1.3)
    - GTMSessionFetcher/Core (< 4.0, >= 1.1)

**Comment by Simon-Zeng** [comment]
> I am facing the same issue even upgraded to GoogleSignIn version 7.0.0 and GTMAppAuth version 2.0.0. But it happening in TestFlight builds and not reproduced in App Store builds yet.

Add "com.google.GIDSignIn" to Keychain Sharing section of Project Capability, and try again.

**Comment by binnilalnamshi** [comment]
> > I am facing the same issue even upgraded to GoogleSignIn version 7.0.0 and GTMAppAuth version 2.0.0. But it happening in TestFlight builds and not reproduced in App Store builds yet.
> 
> Add "com.google.GIDSignIn" to Keychain Sharing section of Project Capability, and try again.

I am not using Keychain Sharing capability in the project, so should I add this capability and add this com.google.GIDSignIn ?

**Comment by goodje** [comment]
I also encounter this issue,  I attached my Podfile.lock at the end.

After I add `Keychain Sharing` in `Signing  & Capabilities`, also a `com.google.GIDSignIn` in Keychain Groups, it solved my issue.

Cheers!
- Xcode: Version 14.2 (14C18)
- Minimum Deployments: macOS 10.15


com.google.GIDSignIn
`Podfile.lock`:
```
PODS:
  - AppAuth (1.6.0):
    - AppAuth/Core (= 1.6.0)
    - AppAuth/ExternalUserAgent (= 1.6.0)
  - AppAuth/Core (1.6.0)
  - AppAuth/ExternalUserAgent (1.6.0):
    - AppAuth/Core
  - GoogleSignIn (7.0.0):
    - AppAuth (~> 1.5)
    - GTMAppAuth (< 3.0, >= 1.3)
    - GTMSessionFetcher/Core (< 4.0, >= 1.1)
  - GTMAppAuth (2.0.0):
    - AppAuth/Core (~> 1.6)
    - GTMSessionFetcher/Core (< 4.0, >= 1.5)
  - GTMSessionFetcher/Core (3.1.0)

DEPENDENCIES:
  - GoogleSignIn

SPEC REPOS:
  trunk:
    - AppAuth
    - GoogleSignIn
    - GTMAppAuth
    - GTMSessionFetcher

SPEC CHECKSUMS:
  AppAuth: 8fca6b5563a5baef2c04bee27538025e4ceb2add
  GoogleSignIn: b232380cf495a429b8095d3178a8d5855b42e842
  GTMAppAuth: 99fb010047ba3973b7026e45393f51f27ab965ae
  GTMSessionFetcher: c9e714f7eec91a55641e2bab9f45fd83a219b882

PODFILE CHECKSUM: acca47bd2cac4d151d614ba463a75f598493389b

COCOAPODS: 1.12.0
```

**Comment by mattisssa** [comment]
OMG, I'm still experiencing the issue on macOS and because of the workaround with the keychain, I see this keychain permission alert. 
Has anyone found another workaround that could help avoid that alert?

**Comment by kubaflo** [comment]
For those of you who added `com.google.GIDSignIn` to the keychains and the error still occurs. Try to remove the bin and obj folder from the project and relaunch the app. It worked for my iOS simulator.

**Comment by hristoenev** [comment]
After updating from GoogleSignIn (7.0.0) to GoogleSignIn (7.1.0) on a macOS app target I got `Error Domain=com.google.GIDSignIn Code=-2 "keychain error" UserInfo={NSLocalizedDescription=keychain error}`. Adding `Keychain Sharing` entitlement and `com.google.GIDSignIn` group to it did not help. After downgrading to GoogleSignIn (7.0.0) and removing the `Keychain Sharing` all is fine, no errors and everything works as expected.

**Comment by hristoenev** [comment]
Don't spend too much time on this. The record the SDK made in Keychain had to be deleted. There are two questions for me:
1. Did the `auth` record broke when the SDK created it?
2. Can the SDK do something if the record is broken?
It is totally fine if the error occurs during development, which means the end users have little chance to experience it. And in any case if it is possible to recover in such situation - it will be great.

**Comment by mdmathias** [comment]
1. I don't think the `auth` record broke when it was saved. My tentative hypothesis is that it was created with a missing entitlement or that your sample on the previous run was missing the entitlement.
2. This case is tricky to remedy because, IIRC, we cannot set a password to the keychain if that item already exists. This is why [we have to try to remove it](https://github.com/google/GTMAppAuth/blob/master/GTMAppAuth/Sources/KeychainStore/KeychainHelper.swift#L121-L128).

**Comment by hristoenev** [comment]
So the SDK created the `auth` record with missing entitlement and at some point in time it decided, that an entitlement is needed. That still does not explain why only switching back and forth between 7.0.0 and 7.1.0 without changing anything else in the project resulted in working with 7.0.0 and failing with 7.1.0

**Comment by apaolino** [comment]
For anyone having the same issue on Flutter MacOS, I solved by using this dependency override:

dependency_overrides:
  google_sign_in_ios: 5.7.5
  
  which uses GoogleSignIn 7.0.0

**Comment by aryan1107** [comment]
@apaolino Thanks so much I was stuck for few hours!

**Comment by vojtabohm** [comment]
Why is this marked closed when the issue still persist in the latest version?

**Comment by anishjain123** [comment]
@krishsatya Were you able to solve this? been stuck on this for the last few hours

**Comment by jungti1234** [comment]
@anishjain123 I'm still stuck too. I really have no idea what's causing that problem.

**Comment by longvudai** [comment]
Downgrade to GoogleSignIn 7.0.0, then add keychain sharing to help me solve this problem.

**Comment by jungti1234** [comment]
> Downgrade to GoogleSignIn 7.0.0, then add keychain sharing to help me solve this problem.

It works! You saved me.

Then what's changed about it since 7.1.0?
To be clear, I hadn't done anything other than update the version of GoogleSignIn to 7.1.0.

**Comment by paulotaylor** [comment]
Just lost a few hours today with this issue. Downgrading GoogleSignIn to version 7 did the trick to me! Why isn't Google taking a deeper look at this more seriously?

**Comment by filipealva** [comment]
> Just lost a few hours today with this issue. Downgrading GoogleSignIn to version 7 did the trick to me! Why isn't Google taking a deeper look at this more seriously?

same here
